### ISSUE TITLE
Invalid cast to PrIndirectReference when the information trailer is not an indirect reference

### ISSUE THREAD

**Issue by jorge-ribeiro-evaltec** [VahidN/iTextSharp.LGPLv2.Core#102]
# Summary of the issue

While generating a signature in a PDF document from a user, we got this exception: `Unable to cast object of type 'iTextSharp.text.pdf.PdfDictionary' to type 'iTextSharp.text.pdf.PrIndirectReference'`

I was able to reproduce the problem using a sample PDF from the library the user uses to generate PDFs.

The problem seems to be that for PDFs generated with this library the Info section of the trailer is not and indirect reference.

## Environment

```
iTextSharp.LGPLv2.Core version: 1.7.4
.NET Core SDK version: 3.1.408
IDE: Microsoft Visual Studio 2019
```

## Example code/Steps to reproduce:

Try signing this PDF: [https://github.com/rkusa/pdfjs/blob/master/test/pdfs/annotations/doc-destination.pdf](https://github.com/rkusa/pdfjs/blob/master/test/pdfs/annotations/doc-destination.pdf)

## Output:

```
Exception message: Unable to cast object of type 'iTextSharp.text.pdf.PdfDictionary' to type 'iTextSharp.text.pdf.PrIndirectReference'.
Full Stack trace: System.InvalidCastException: Unable to cast object of type 'iTextSharp.text.pdf.PdfDictionary' to type 'iTextSharp.text.pdf.PrIndirectReference'.
   at iTextSharp.text.pdf.PdfStamperImp.Close(Hashtable moreInfo)
   at iTextSharp.text.pdf.PdfSignatureAppearance.PreClose(Hashtable exclusionSizes)
   at InternalLibrary.Pdf.Internal.PdfDocument.ReadContent(DateTime signingTime, String name, String filter, String subFilter, Int32 signatureSize, X509Certificate[] chain)
   --- End of inner exception stack trace ---
...
```

**Comment by jorge-ribeiro-evaltec** [comment]
I've created a PR with the fix for this issue: https://github.com/VahidN/iTextSharp.LGPLv2.Core/pull/103
