### ISSUE TITLE
Object null refrence while adding table to document

### ISSUE THREAD

**Issue by troncomputers** [VahidN/iTextSharp.LGPLv2.Core#12]
Hello. Please help!

There is too much code so here is .txt file with whole function.
[function.txt](https://github.com/VahidN/iTextSharp.LGPLv2.Core/files/1095694/function.txt)

Exception:
Object reference not set to an instance of an object.

Stack:
   at iTextSharp.text.pdf.PdfPTable.GetRowHeight(Int32 idx, Boolean firsttime)
   at iTextSharp.text.pdf.ColumnText.GoComposite(Boolean simulate)
   at iTextSharp.text.pdf.ColumnText.Go(Boolean simulate)
   at iTextSharp.text.pdf.PdfDocument.AddPTable(PdfPTable ptable)
   at iTextSharp.text.pdf.PdfDocument.Add(IElement element)
   at iTextSharp.text.Document.Add(IElement element)
   at OptimoKasiarz.Data.Classes.Methods.WydrukTest(IHostingEnvironment _hostingEnvironment, Urzedy us, Podatnicy p, UrzadzeniaPodatnika up) in C:\OptimoKasiarz\OptimoKasiarz\Data\Classes\Methods.cs:line 309

I copied this function from my older, desktop app where iTextSharp was in ver.: 5.5.9.0

**Comment by VahidN** [comment]
- I added [a null check for it](https://github.com/VahidN/iTextSharp.LGPLv2.Core/commit/3dc0f5e1df436133143a6c1c6d1545b5e3f6930a). Try V1.3.1.
- Also you should know that this version doesn't support rowspans correctly (actually iTextSharp supports row spans correctly since v5.4.3, not before that). you should use `nested tables` to produce what you want.
