### ISSUE TITLE
Tests fail on Mac and Linux due to String.IndexOf inconsistencies 

### ISSUE THREAD

**Issue by jcramer** [VahidN/iTextSharp.LGPLv2.Core#2]
Thanks for creating this port, VahidN! Great work!

I just wanted to point out that most of the functional tests fail on platforms other than windows.  I think the issue lies in the difference in string IndexOf as referenced in this issue here: https://github.com/dotnet/coreclr/issues/6087

**Comment by VahidN** [comment]
Thank you.
What exceptions are reported? These tests need some modifications to run on Linux. For instance in the TestUtils class, [c:\windows\fonts](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/TestUtils.cs#L41) is defined as the fonts folder or [GetBaseDir](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/TestUtils.cs#L19) should be adjusted too.

**Comment by jcramer** [comment]
I did notice the issue with the font paths, but the error that hits right away seems to be this other issue. Here's an example of the text exception:

Error Message:
   Test method iTextSharp.LGPLv2.Core.FunctionalTests.RtfTests.Verify_PDF_To_RTF_File_CanBeCreated threw exception:
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
Stack Trace:
    at System.String.Substring(Int32 startIndex, Int32 length)
   at iTextSharp.LGPLv2.Core.FunctionalTests.TestUtils.GetBaseDir() in /lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core.FunctionalTests/TestUtils.cs:line 20
   at iTextSharp.LGPLv2.Core.FunctionalTests.TestUtils.GetOutputFolder() in /lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core.FunctionalTests/TestUtils.cs:lin
e 25
   at iTextSharp.LGPLv2.Core.FunctionalTests.RtfTests.Verify_PDF_To_RTF_File_CanBeCreated() in /lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core.FunctionalTes
ts/RtfTests.cs:line 19


I dropped in a couple of WriteLines in for debugging within my docker container, to see what the root and idx values were. Here's the modifed method and console output:

```
public static string GetBaseDir()
{
           var currentAssembly = typeof(TestUtils).GetTypeInfo().Assembly;
           var root = Path.GetDirectoryName(currentAssembly.Location);
           var idx = root.IndexOf(@"\bin", StringComparison.OrdinalIgnoreCase);
           Console.WriteLine("Print root:" + root);
           Console.WriteLine("Print idx:" + idx);

           return root.Substring(0, idx);
}
```

 Output:
```
Print root: /lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core.FunctionalTests/bin/Debug/netcoreapp1.0

Print idx: -1
```
The index should obviously not equal to -1.

**Comment by jcramer** [comment]
ok and now this issue was fixed by just removing the @ symbol in this line:

`var idx = root.IndexOf(@"\bin", StringComparison.OrdinalIgnoreCase);`

Must be something to do with support for string literals..?

**Comment by VahidN** [comment]
`GetBaseDir()` is not an important method. You can replace it with the following path on your system:
```csharp
return  "/lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core.FunctionalTests/bin/";
```
Final produced PDF files will be stored there.

**Comment by VahidN** [comment]
This issue can be fixed by using a platform specific directory separator char:
```csharp
var idx = root.IndexOf($"{Path.DirectorySeparatorChar}bin", StringComparison.OrdinalIgnoreCase);
```
Also I updated the repository to reflected these changes.

**Comment by jcramer** [comment]
Thank you. That works perfect! 👍 👍  Now 46/60 tests passing...   

Here is the next type of error below. The next different type of error is a FileNotFoundException, It looks like the root path gets preppended to whole resource path for the image.  Any pdf looking for a resource has the same issue.

```
Failed   Verify_iTextXML_To_PDF_File_CanBeCreated
Error Message:
   Test method iTextSharp.LGPLv2.Core.FunctionalTests.XmlITextTests.Verify_iTextXML_To_PDF_File_CanBeCreated threw exception:
System.IO.FileNotFoundException: Could not find file '/lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core.FunctionalTests/\\lib\iTextSharp.LGPLv2.Core\src\iText
Sharp.LGPLv2.Core.FunctionalTests\iTextExamples\resources\img\hitchcock.png'.
Stack Trace:
    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at iTextSharp.LGPLv2.Core.System.NetUtils.WebUtils.GetResponseStream(Uri url) in /lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core/System/NetUtils/WebUtils
.cs:line 15
   at iTextSharp.text.Image.GetInstance(Uri url) in /lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core/iTextSharp/text/Image.cs:line 938
   at iTextSharp.text.Image.GetInstance(String filename) in /lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core/iTextSharp/text/Image.cs:line 1353
   at iTextSharp.text.factories.ElementFactory.GetImage(Properties attributes) in /lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core/iTextSharp/text/factories/
ElementFactory.cs:line 227
   at iTextSharp.text.xml.TextHandler.HandleStartingTags(String name, Properties attributes) in /lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core/iTextSharp/t
ext/xml/ITextHandler.cs:line 656
   at iTextSharp.text.xml.TextHandler.StartElement(String uri, String lname, String name, Hashtable attrs) in /lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Cor
e/iTextSharp/text/xml/ITextHandler.cs:line 853
   at iTextSharp.text.xml.ParserBase.Parse(XmlReader reader) in /lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core/iTextSharp/text/xml/ParserBase.cs:line 59
   at iTextSharp.text.xml.XmlParser.Go(IDocListener document, XmlReader reader) in /lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core/iTextSharp/text/xml/XmlPa
rser.cs:line 134
   at iTextSharp.LGPLv2.Core.FunctionalTests.XmlITextTests.converITextXmlToPdfFile(String iTextXML, String pdfFilePath) in /lib/iTextSharp.LGPLv2.Core/src/iTextSha
rp.LGPLv2.Core.FunctionalTests/XmlITextTests.cs:line 2000
   at iTextSharp.LGPLv2.Core.FunctionalTests.XmlITextTests.Verify_iTextXML_To_PDF_File_CanBeCreated() in /lib/iTextSharp.LGPLv2.Core/src/iTextSharp.LGPLv2.Core.Fun
ctionalTests/XmlITextTests.cs:line 52
```

**Comment by VahidN** [comment]
[It's fixed now](https://github.com/VahidN/iTextSharp.LGPLv2.Core/commit/f42d3419f4e255d128f34985ae09d3459e0c1fd7)
![lintext](https://cloud.githubusercontent.com/assets/766010/18975934/d6538342-86ba-11e6-8912-946612622ef1.png)

**Comment by jcramer** [comment]
Confirmed. Great work.
