### ISSUE TITLE
Error when creating PDF in RowSpanAbove method

### ISSUE THREAD

**Issue by yaguiman** [VahidN/iTextSharp.LGPLv2.Core#27]
# Summary of the issue
When we create a PDF in certain cases the component throws an exception:

Error Pdf System.NullReferenceException: Object reference not set to an instance of an object.
   at iTextSharp.text.pdf.PdfPTable.RowSpanAbove(Int32 currRow, Int32 currCol)

## Output:

```
Exception message: Error Pdf System.NullReferenceException: Object reference not set to an instance of an object.
Full Stack trace:
Error Pdf System.NullReferenceException: Object reference not set to an instance of an object.
   at iTextSharp.text.pdf.PdfPTable.RowSpanAbove(Int32 currRow, Int32 currCol)
   at iTextSharp.text.pdf.PdfPTable.GetRowHeight(Int32 idx, Boolean firsttime)
   at iTextSharp.text.pdf.ColumnText.GoComposite(Boolean simulate)
   at iTextSharp.text.pdf.ColumnText.Go(Boolean simulate)
   at iTextSharp.text.pdf.PdfPCell.GetMaxHeight()
   at iTextSharp.text.pdf.PdfPRow.CalculateHeights()
   at iTextSharp.text.pdf.PdfPRow.SplitRow(PdfPTable table, Int32 rowIndex, Single new_height)
   at iTextSharp.text.pdf.ColumnText.GoComposite(Boolean simulate)
   at iTextSharp.text.pdf.ColumnText.Go(Boolean simulate)
   at iTextSharp.text.pdf.PdfDocument.AddPTable(PdfPTable ptable)
   at iTextSharp.text.pdf.PdfDocument.Add(IElement element)
   at iTextSharp.text.Document.Add(IElement element)
```
## Fix:

We cloned the project and debugged it in order to find why we're getting this error.
We found that the problem is at line 1365 of PdfPTable class:

_while ((aboveCell == null) && (row > 0))
            {
                aboveRow = (PdfPRow)rows[--row];
                aboveCell = aboveRow.GetCells()[currCol];
            }_

We did a modification in the while to handle aboveRow object in case it would be null:

_while ((aboveCell == null) && (row > 0))
            {
                aboveRow = (PdfPRow)rows[--row];
                **if (aboveRow == null) return false;**
                aboveCell = aboveRow.GetCells()[currCol];
            }_

With this modification the component worked like a charm.

It would great if you can include this modification in the future releases of the component.
**I also should mention that you did a good job porting iTextSharp to .NET core.**

**Comment by VahidN** [comment]
Thanks. Fixed via #https://github.com/VahidN/iTextSharp.LGPLv2.Core/commit/1a427f5c1652a61ea8290d05a74948b8555a82a3
