### ISSUE TITLE
Font 'STSongStd-Light' with 'UniGB-UCS2-H' is not recognized.

### ISSUE THREAD

**Issue by lizhizhang** [VahidN/iTextSharp.LGPLv2.Core#34]
Hello, I meet a problem that when I  try to use 'SetField' ,it raises '{iTextSharp.text.DocumentException: Font 'STSongStd-Light' with 'UniGB-UCS2-H' is not recognized.
   at iTextSharp.text.pdf.BaseFont.CreateFont(String name, String encoding, Boolean embedded, Boolean cached, Byte[] ttfAfm, Byte[] pfb, Boolean noThrow, Boolean forceRead)
   at iTextSharp.text.pdf.DocumentFont..ctor(PrIndirectReference refFont)
   at iTextSharp.text.pdf.AcroFields.DecodeGenericDictionary(PdfDictionary merged, BaseField tx)
   at iTextSharp.text.pdf.AcroFields.GetAppearance(PdfDictionary merged, String text, String fieldName)
   at iTextSharp.text.pdf.AcroFields.SetField(String name, String value, String display)'

**Comment by VahidN** [comment]
Follow this sample about "[Fill out a PDF form using iTextSharp for .NET core](https://medium.com/@taithienbo/fill-out-a-pdf-form-using-itextsharp-for-net-core-4b323cb58459)"

**Comment by lizhizhang** [comment]
Thank your sample,but it can not help me.Because it can not work with Chinese char.And can you show me your e-mail address,and I hope to send you my demo.Thank you very much!

**Comment by VahidN** [comment]
Please attach your .zip file here. Just drag & drop it to the editor.

**Comment by VahidN** [comment]
I ported some missing map files from the https://github.com/LibrePDF/OpenPDF project. Now it works with Font 'STSongStd-Light' and 'UniGB-UCS2-H' encoding, [using these tests](https://github.com/VahidN/iTextSharp.LGPLv2.Core/blob/master/src/iTextSharp.LGPLv2.Core.FunctionalTests/Issues/Issue34.cs):
![issue34](https://user-images.githubusercontent.com/766010/54012387-25af0f00-418b-11e9-85b8-508e85170dec.png)
